### ISSUE TITLE
Please add some information to the readme

### ISSUE THREAD

**Issue by Giszmo** [Dolu89/chastr#1]
Searching the project's code I see kind 4 has some special role but I could not find if this client is compatible with nip-4.

Are the Android and iPhone apps on the stores?

**Comment by Dolu89** [comment]
This project isn't finished and i'm not sure to continue it.
If you compile it yourself, you will see a pretty empty app

**Comment by Giszmo** [comment]
So would you mind if I removed a link to it from awesome-nostr? I'd add another link to find all github projects [tagged with nostr](https://github.com/topics/nostr), so people could still easily find your work.

**Comment by Dolu89** [comment]
Yes please, remove it
